export const templateStrings = {
    'documentActivity.1': '{{userName}} pushed Draft <b>{{resourceName}}</b> to Live',
    'documentActivity.2': '{{userName}} created a draft <b>{{resourceName}}</b>',
    'documentActivity.3': '{{userName}} renamed Draft <b>{{oldName}}</b> to <b>{{newName}}</b>',
    'documentActivity.4': '{{userName}} deleted Draft <b>{{resourceName}}</b>',
    'documentActivity.5': '{{userName}} changed node <b>{{nodeName}}</b> location from <b>{{oldParentName}}</b> to <b>{{newParentName}}</b>',
    'documentActivity.6': '{{userName}} added tags {{tag}}',
    'documentActivity.7': '{{userName}} removed tags {{tag}}',
    'documentActivity.8': '{{userName}} updated the Node Short Title - <b>{{nodeName}}</b>',
    'documentActivity.9': '{{userName}} updated the Node Title- <b>{{nodeName}}</b>',
    'documentActivity.10': '{{userName}} updated the Node File Name- <b>{{nodeName}}</b>',

    'operationStatus.1.1': '{{projectName}} Creation pending <br/> <small>creating a project<b> {{projectName}} </b> is in progress</small>',
    'operationStatus.1.2': '{{projectName}} Created <br/> <small>creating a project <b>{{projectName}}</b> is successful</small>',
    'operationStatus.1.3': '{{projectName}} Creation failed <br/> <small>creating a project <b>{{projectName}}</b> is failed</small>',
    'operationStatus.12.1': '{{draftName}} Accept to live pending<br/><small>accept draft <b>{{draftName}}</b> to live is in progress</small>',
    'operationStatus.12.2': '{{draftName}} Accept to live Successful<br/><small>accept draft <b>{{draftName}}</b> to live is successful</small>',
    'operationStatus.12.3': '{{draftName}} Accept to live failed<br/><small>accept draft <b>{{draftName}}</b> to live is failed</small>',
    'operationStatus.4.1': '{{distributionName}} Creation pending <br/> <small>creating distribution <b>{{distributionName}}</b> in {{projectName}} is in progress</small>',
    'operationStatus.4.2': '{{distributionName}} Created <br/> <small>creating distribution <b>{{distributionName}}</b> in {{projectName}} is successful</small>',
    'operationStatus.4.3': '{{distributionName}} Creation failed <br/> <small>creating distribution <b>{{distributionName}}</b> in {{projectName}} is failed </small>',
    'operationStatus.17.1': '{{draftName}} Creation pending <br/> <small>creating a draft <b>{{draftName}}</b> in {{nodeName}} is in progress</small>',
    'operationStatus.17.2': '{{draftName}} Created <br/> <small>creating a draft <b>{{draftName}}</b> in {{nodeName}} is successful</small>',
    'operationStatus.17.3': '{{draftName}} Creation failed <br/> <small>creating a draft <b>{{draftName}}</b> in {{nodeName}} is failed</small>',
    'operationStatus.18.1': '{{nodeName}} addition pending <br/> <small>adding a node<b> {{nodeName}} </b> is in progress</small>',
    'operationStatus.18.2': '{{nodeName}} added <br/> <small>adding a node <b>{{nodeName}}</b> is successful</small>',
    'operationStatus.18.3': '{{nodeName}} addition failed <br/> <small>adding a node <b>{{nodeName}}</b> is failed</small>',
    'operationStatus.26.1': '{{tagGroupName}} Creation pending <br/> <small>creating a tag group<b> {{tagGroupName}} </b> is in progress</small>',
    'operationStatus.26.2': '{{tagGroupName}} Created <br/> <small>creating a tag group <b>{{tagGroupName}}</b> is successful</small>',
    'operationStatus.26.3': '{{tagGroupName}} Creation failed <br/> <small>creating a tag group <b>{{tagGroupName}}</b> is failed</small>',
    'operationStatus.27.1': '{{tagGroupName}} editing pending <br/> <small>editing a tag group<b> {{tagGroupName}} </b> is in progress</small>',
    'operationStatus.27.2': '{{tagGroupName}} edited <br/> <small>editing a tag group <b>{{tagGroupName}}</b> is successful</small>',
    'operationStatus.27.3': '{{tagGroupName}} editing failed <br/> <small>editing a tag group <b>{{tagGroupName}}</b> is failed</small>',
    'operationStatus.28.1': '{{tagName}} Creation pending <br/> <small>creating tag <b>{{tagName}}</b> in {{tagGroupName}} is in progress</small>',
    'operationStatus.28.2': '{{tagName}} Created <br/> <small>creating tag <b>{{tagName}}</b> in {{tagGroupName}} is successful</small>',
    'operationStatus.28.3': '{{tagName}} Creation failed <br/> <small>creating tag <b>{{tagName}}</b> in {{tagGroupName}} is failed </small>',
    'operationStatus.29.1': '{{tagName}} editing pending <br/> <small>editing a tag <b>{{tagName}} </b> is in progress</small>',
    'operationStatus.29.2': '{{tagName}} edited <br/> <small>editing a tag <b>{{tagName}}</b> is successful</small>',
    'operationStatus.29.3': '{{tagName}} editing failed <br/> <small>editing a tag <b>{{tagName}}</b> is failed</small>',
    'operationStatus.30.1': '{{tagGroupName}} addition pending <br/> <small>adding tag group <b>{{tagGroupName}}</b> to {{projectName}} is in progress</small>',
    'operationStatus.30.2': '{{tagGroupName}} added <br/> <small>adding tag group <b>{{tagGroupName}}</b> to {{projectName}} is successful</small>',
    'operationStatus.30.3': '{{tagGroupName}} addition failed <br/> <small>adding tag group <b>{{tagGroupName}}</b> to {{projectName}} is failed </small>',
    'operationStatus.35.1': '{{fileName}} updation pending <br/> <small>updating an asset <b>{{fileName}} </b> is in progress</small>',
    'operationStatus.35.2': '{{fileName}} updated <br/> <small>updating an asset <b>{{fileName}}</b> is successful</small>',
    'operationStatus.35.3': '{{fileName}} updation failed <br/> <small>updating an asset <b>{{fileName}}</b> is failed</small>',
    'operationStatus.37.1': '{{distributionName}} publish pending <br/> <small>publishing a distribution<b> {{distributionName}} </b> is in progress</small>',
    'operationStatus.37.2': '{{distributionName}} publish <br/> <small>publishing a distribution <b>{{distributionName}}</b> is successful</small>',
    'operationStatus.37.3': '{{distributionName}} publish failed <br/> <small>publishing a distribution <b>{{distributionName}}</b> is failed</small>',
    'operationStatus.38.1': '{{tagName}} addition pending <br/> <small>adding tag <b>{{tagName}}</b> to {{nodeName}} is in progress</small>',
    'operationStatus.38.2': '{{tagName}} added <br/> <small>adding tag <b>{{tagName}}</b> to {{nodeName}} is successful</small>',
    'operationStatus.38.3': '{{tagName}} addition failed <br/> <small>adding tag <b>{{tagName}}</b> to {{nodeName}} is failed </small>',
    'operationStatus.40.1': '{{tagName}} removal pending <br/> <small>removing tag <b>{{tagName}}</b> from {{nodeName}} is in progress</small>',
    'operationStatus.40.2': '{{tagName}} removed <br/> <small>removing tag <b>{{tagName}}</b> from {{nodeName}} is successful</small>',
    'operationStatus.40.3': '{{tagName}} removal failed <br/> <small>removing tag <b>{{tagName}}</b> from {{nodeName}} is failed </small>',
    'operationStatus.44.1': '{{nodeName}} change location pending <br/> <small>moving node <b>{{nodeName}}</b> to {{parentNodeName}} is in progress</small>',
    'operationStatus.44.2': '{{nodeName}} location changed <br/> <small>moving node <b>{{nodeName}}</b> to {{parentNodeName}} is successful</small>',
    'operationStatus.44.3': '{{nodeName}} change location failed <br/> <small>moving node <b>{{nodeName}}</b> to {{parentNodeName}} is failed </small>',
    'operationStatus.48.1': '{{oldDraftName}} rename pending <br/> <small>renaming draft <b>{{oldDraftName}}</b> to {{newDraftName}} is in progress</small>',
    'operationStatus.48.2': '{{oldDraftName}} renamed <br/> <small>renaming draft <b>{{oldDraftName}}</b> to {{newDraftName}} is successful</small>',
    'operationStatus.48.3': '{{oldDraftName}} rename failed <br/> <small>renaming draft <b>{{oldDraftName}}</b> to {{newDraftName}} is failed </small>',
    'operationStatus.49.1': '{{tagGroupName}} removal pending <br/> <small>removing tag group <b>{{tagGroupName}}</b> from {{projectName}} is in progress</small>',
    'operationStatus.49.2': '{{tagGroupName}} removed <br/> <small>removing tag group <b>{{tagGroupName}}</b> from {{projectName}} is successful</small>',
    'operationStatus.49.3': '{{tagGroupName}} removal failed <br/> <small>removing tag group <b>{{tagGroupName}}</b> from {{projectName}} is failed </small>',
    'operationStatus.51.1': '{{draftName}} Creation pending <br/> <small>creating a draft <b> {{draftName}}</b> with snapshot is in progress</small>',
    'operationStatus.51.2': '{{draftName}} Created <br/> <small>creating a draft <b>{{draftName}}</b> with snapshot is successful</small>',
    'operationStatus.51.3': '{{draftName}} Creation failed <br/> <small>creating a draft <b>{{draftName}}</b> with snapshot is failed</small>',
    'operationStatus.58.1': '{{userName}} assigning or unassigning pending <br/> <small>assigning or unassigning <b>{{userName}}</b> as system admin is in progress</small>',
    'operationStatus.58.2': '{{userName}} assigned or unassigned <br/> <small>assigning or unassigning <b>{{userName}}</b> as system admin is successful</small>',
    'operationStatus.58.3': '{{userName}} assigning or unassigning failed <br/> <small>assigning or unassigning <b>{{userName}}</b> as system admin is failed </small>',
    'operationStatus.63.1': '{{userName}} assigning or unassigning pending <br/> <small>assigning or unassigning <b>{{userName}}</b> to {{projectName}} as admin is in progress</small>',
    'operationStatus.63.2': '{{userName}} assigned or unassigned <br/> <small>assigning or unassigning <b>{{userName}}</b> to {{projectName}} as admin is successful</small>',
    'operationStatus.63.3': '{{userName}} assigning or unassigning <br/> <small>assigning or unassigning <b>{{userName}}</b> to {{projectName}} as admin is failed </small>',
    'operationStatus.61.1': '{{draftName}} deletion pending <br/> <small>deleting a draft <b>{{draftName}}</b> from {{nodeName}} is in progress</small>',
    'operationStatus.61.2': '{{draftName}} deleted <br/> <small>deleting a draft <b>{{draftName}}</b> from {{nodeName}} is successful</small>',
    'operationStatus.61.3': '{{draftName}} deletion failed <br/> <small>deleting a draft <b>{{draftName}}</b> from {{nodeName}} is failed </small>',
    'operationStatus.65.1': '{{nodeName}} deletion pending <br/> <small>deleting a node<b> {{nodeName}} </b> is in progress</small>',
    'operationStatus.65.2': '{{nodeName}} deleted <br/> <small>deleting a node <b>{{nodeName}}</b> is successful</small>',
    'operationStatus.65.3': '{{nodeName}} deletion failed <br/> <small>deleting a node <b>{{nodeName}}</b> is failed</small>',
    'operationStatus.69.1': 'Profile pic upload in progress',
    'operationStatus.69.2': 'Profile pic uploaded',
    'operationStatus.69.3': 'Profile pic upload failed',
    'operationStatus.71.1': 'Profile pic delete in progress',
    'operationStatus.71.2': 'Profile pic deleted',
    'operationStatus.71.3': 'Profile pic delete failed',
    'operationStatus.21.1': '{{assetName}} upsert asset pending <br/> <small>upsert asset <b>{{assetName}}</b> is in progress</small>',
    'operationStatus.21.2': '{{assetName}} upsert asset success <br/> <small>upsert asset <b>{{assetName}}</b> is successful</small>',
    'operationStatus.21.3': '{{assetName}} upsert asset failed <br/> <small>upsert asset <b>{{assetName}}</b> is failed</small>',
    'operationStatus.75.1': '{{draftName}} Creation pending <br/> <small>creating a draft <b> {{draftName}}</b> with snapshot is in progress</small>',
    'operationStatus.75.2': '{{draftName}} Created <br/> <small>creating a draft <b>{{draftName}}</b> with snapshot is successful</small>',
    'operationStatus.75.3': '{{draftName}} Creation failed <br/> <small>creating a draft <b>{{draftName}}</b> with snapshot is failed</small>',
    'operationStatus.43.1': '{{nodeName}} update pending <br/> <small>updating a node<b> {{nodeName}} </b> is in progress</small>',
    'operationStatus.43.2': '{{nodeName}} update <br/> <small>udating a node <b>{{nodeName}}</b> is successful</small>',
    'operationStatus.43.3': '{{nodeName}} updation failed <br/> <small>updation of a node <b>{{nodeName}}</b> is failed</small>',
    'operationStatus.80.1': 'Import Distribution for distribution: {{distributionName}} is pending',
    'operationStatus.80.2': 'Import Distribution for distribution: {{distributionName}} is succeed',
    'operationStatus.80.3': 'Import Distribution for distribution: {{distributionName}} is failed',

    'realtimeUpdates.1': '{{userName}} created a Project <b>{{resourceName}}</b>',
    'realtimeUpdates.2': '{{userName}} created a Distribution <b>{{resourceName}}</b> to Project {{projectName}}',
    'realtimeUpdates.3': '{{userName}} added a Node <b>{{resourceName}}</b> to Distribution {{distributionName}}, Project {{projectName}}',
    'realtimeUpdates.4': '{{userName}} deleted a Node <b>{{resourceName}}</b> from Distribution {{distributionName}}, Project {{projectName}}',
    'realtimeUpdates.5': '{{userName}} created a Draft <b>{{resourceName}}</b> to Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
    'realtimeUpdates.6': '{{userName}} deleted a Draft <b>{{resourceName}}</b> to Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
    'realtimeUpdates.7': '{{userName}} edited a Draft <b>{{resourceName}}</b> to Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
    'realtimeUpdates.8': '{{userName}} edited a Node <b>{{resourceName}}</b> to Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
    'realtimeUpdates.9': '{{userName}} renamed a Draft <b>{{oldName}}</b> to <b>{{newName}}</b> in Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
    'realtimeUpdates.10': '{{userName}} edited a Distribution <b>{{resourceName}}</b> to Project {{projectName}} ',
    'realtimeUpdates.11': '{{userName}} edited a Project <b>{{resourceName}}</b>',
    'realtimeUpdates.12': '{{userName}} accept a Draft to Live <b>{{resourceName}}</b> from Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',

    'personalUpdates.1': '{{userName}} created a Project <b>{{resourceName}}</b>',
    'personalUpdates.2': '{{userName}} created a Distribution <b>{{resourceName}}</b> to Project {{projectName}}',
    'personalUpdates.3': '{{userName}} added a Node <b>{{resourceName}}</b> to Distribution {{distributionName}}, Project {{projectName}}',
    'personalUpdates.4': '{{userName}} deleted a Node <b>{{resourceName}}</b> from Distribution {{distributionName}}, Project {{projectName}}',
    'personalUpdates.5': '{{userName}} created a Draft <b>{{resourceName}}</b> to Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
    'personalUpdates.6': '{{userName}} deleted a Draft <b>{{resourceName}}</b> to Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
    'personalUpdates.7': '{{userName}} edited a Draft <b>{{resourceName}}</b> to Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
    'personalUpdates.8': '{{userName}} edited a Node <b>{{resourceName}}</b> to Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
    'personalUpdates.9': '{{userName}} renamed a Draft <b>{{resourceName}}</b> in Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
    'personalUpdates.10': '{{userName}} edited a Distribution <b>{{resourceName}}</b> to Project {{projectName}} ',
    'personalUpdates.11': '{{userName}} edited a Project <b>{{resourceName}}</b>',
    'personalUpdates.12': '{{userName}} accept a Draft to Live <b>{{resourceName}}</b> from Node {{shortTitle}}, Distribution {{distributionName}}, Project {{projectName}} ',
};

